-- AlterTable
ALTER TABLE "events" ADD COLUMN     "saleEndTime" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "saleStartTime" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "saleStatus" TEXT NOT NULL DEFAULT 'on_sale';
